### ISSUE TITLE
Per App Settings only available to system apps

### ISSUE THREAD

**Issue by archerallstars** [pia-foss/mobile-android-legacy#18]
I don't see per apps setting for user installed apps as shown in the screenshot below:

![Screenshot_2021-12-21-11-42-07-209](https://user-images.githubusercontent.com/1403194/146993193-f5914539-4ff1-4da6-a889-a38c269874f9.jpeg)

### My device info:

- Lenovo Tab P11, TB-J606L
- Android 11
- PIA version: 3.12.4 (571) - playstore

**Comment by 1366613** [comment]
Any update on this?

**Comment by Gronsak** [comment]
Can confirm that this is an issue for me aswell, been running 3.12.3 (10570) sideloaded as a workaround for a while and tried the newest sideload version and playstore version today to see if anything had changed but nothing yet.

This is version 3.16.0 (577)
![Screenshot_20221030-134133](https://user-images.githubusercontent.com/4255265/198879532-03ce9943-97a5-4ffc-9b94-6ca5beed6869.png)

Version 3.16.0 (10577)
![Screenshot_20221030-135228](https://user-images.githubusercontent.com/4255265/198879588-3e955ace-65bd-4af6-aa4d-50cb81e69f11.png)

Version 3.12.3 (10570)
![Screenshot_20221030-135941](https://user-images.githubusercontent.com/4255265/198879767-b8c8c935-00c0-487c-82ae-f96c0b5f1185.png)

This is not the only app missing from the list, Google Home is also missing to give an example, but the one I need to work.

Hardware info:
Sony Xperia 1 III
Android 12 (61.1.A.11.36)

**Comment by Gronsak** [comment]
To clarify though, I don't think it's limited to just system apps for me, Battle.net authenticator still shows up for example, but alot of apps are indead missing for some reason.

**Comment by Gronsak** [comment]
Just tested 3.17.0 (579) and am still experiencing the issue

**Comment by ThoSap** [comment]
Is there any update on this?

**Comment by zackarno** [comment]
Same issue here. Alot of apps missing from "Per Apps Settings"

It looks like many users face the same issue:

https://www.reddit.com/r/PrivateInternetAccess/comments/rc6axp/per_app_settings_on_android/

https://www.reddit.com/r/PrivateInternetAccess/comments/uz19uv/android_per_app_settings_doesnt_show_all_apps/

**Comment by Gronsak** [comment]
I've been in contact with support about this issue a couple of times and the responses has varied between "we've never heard of this before!" and "the development team is working to resolve the issue, it should be fixed in the next patch!".
I've gotten some variation of the first response after I've gotten the second response so either the support team is not all up to date on the current known issues or someone is lying.

Doesn't really seem to be much developer activity here on GitHub either so I don't know if any issues are actually monitored...

**Comment by nethershaw** [comment]
Really? Nothing for two years?

**Comment by max246** [comment]
Most likely is the check when the adaptor is getting populated. 
It seems like they should use `checkSelfPermission `which is a safer and correct way to check the permission.

Not sure why it would filter out too much since many apps should have the permission to have internet access

https://github.com/pia-foss/android/blob/2413ef5cd2a6c839010fcf4692789d994975576f/app/src/main/java/com/privateinternetaccess/android/ui/tv/fragments/PerAppFragment.java#L178C66-L178C66

**Comment by kp-juan-docal** [comment]
hello everyone! first of all, apologies for the unfogivable delay on the reply. I believe this is something that has been addressed and it should no longer be the case on version `3.19.2`. If you face it again, please feel free to create a new issue. We are working to keep a closer look at the issues reported here 🙇

**Comment by Gronsak** [comment]
Can confirm that this issue is finally fixed and per app settings actually show all apps again.
