### ISSUE TITLE
keep adding releases and changelogs

### ISSUE THREAD

**Issue by piramiday** [pia-foss/mobile-android-legacy#7]
re-opening #3 -- no sign of current version 3.7.0 here, or its changelog anywhere.

is PIA really serious about publishing its apps as open source repositories?

**Comment by piramiday** [comment]
no sign of version 3.7.4 or 3.8.0 either! @jaspws?

**Comment by 8227846265** [comment]
I'm also curious since there's nothing on the Releases nor any change log. I'm doubting as well whether PIA is really going open source with the apps.

**Comment by piramiday** [comment]
no version 3.8.1, no version 3.8.2 -- PIA is not serious about open sourcing its application.

closing this issue out of disappointment. :-1:

**Comment by 8pen-s8urce** [comment]
Hello. At the moment of writing this, I think that this issue should be reopened because the source code of PIA's android application was last updated more than one year ago, as well as other repositories here.

Although this repository hasn't seen much development lately, I noticed that @kp-juan-docal, someone that seems to be working at PIA started closing some old issues and answering to people here in Github.

This recent activity and the apologies from the person saying that PIA will start giving more attention to people's issues reported here gives me hope about this repository, but nothing is guaranteed.

Also we should hold the company accountable for the misleading marketing in their website where they state that "Our apps are 100% open source. Anybody can inspect and customize our open-source software.", when currently that's not true.

In fact, I will open an issue here in Github regarding the misleading marketing.

That's it and have a nice day.
